"use server";

import prisma from "@/lib/prisma";
import { getTenantContext } from "../utils/tenant-context";

// 1. Fetch consent details via public token
export async function getConsentByTokenAction(token: string) {
    try {
        const consent = await prisma.studentConsent.findUnique({
            where: { token },
            include: {
                student: {
                    select: {
                        id: true,
                        firstName: true,
                        lastName: true,
                        family: { select: { fatherName: true, fatherPhone: true } },
                        address: { select: { currentAddress: true } },
                        academic: { select: { classId: true } },
                    }
                },
                academicYear: {
                    select: { name: true }
                }
            }
        });

        if (!consent) {
            return { success: false, error: "Invalid or expired consent link." };
        }

        return { success: true, data: consent };
    } catch (error: any) {
        console.error("Get Consent Error:", error);
        return { success: false, error: "Failed to load consent details." };
    }
}

// 2. Parent Submits Consent
export async function submitConsentAction(token: string, data: { updatedPhone?: string, updatedAddress?: string, consentStatus: "Confirmed" | "Declined" }) {
    try {
        const consent = await prisma.studentConsent.findUnique({ where: { token } });
        if (!consent) throw new Error("Invalid token");

        if (consent.consentStatus !== "Pending") {
            return { success: false, error: "Consent has already been submitted." };
        }

        // Transaction to update consent AND conditionally promote student
        const result = await prisma.$transaction(async (tx: any) => {
            // Update consent record
            const updatedConsent = await tx.studentConsent.update({
                where: { token },
                data: {
                    consentStatus: data.consentStatus,
                    updatedPhone: data.updatedPhone,
                    updatedAddress: data.updatedAddress,
                    submittedAt: new Date(),
                }
            });

            // If confirmed, update student main record relations
            if (data.consentStatus === "Confirmed") {
                if (data.updatedPhone) {
                    await tx.familyDetail.updateMany({
                        where: { studentId: consent.studentId },
                        data: { fatherPhone: data.updatedPhone }
                    });
                }
                if (data.updatedAddress) {
                    await tx.address.updateMany({
                        where: { studentId: consent.studentId },
                        data: { currentAddress: data.updatedAddress }
                    });
                }

                // Note: The actual "Promotion" (AcademicHistory) might need manual class mapping 
                // (e.g., passing from Class 1 to Class 2). This could be done here or in a bulk 
                // admin action later. For now, we secure their consent.
            }

            return updatedConsent;
        });

        return { success: true, data: result };
    } catch (error: any) {
        console.error("Submit Consent Error:", error);
        return { success: false, error: "Failed to submit consent." };
    }
}

// 3. Admin generates consent links for a specific class/year
export async function generateConsentLinksAction(classId: string, targetingAcademicYearId: string) {
    try {
        const context = await getTenantContext();
        
        // Find all active students in this class
        const students = await prisma.student.findMany({
            where: {
                schoolId: context.schoolId,
                academic: { classId: classId }
            }
        });

        let createdCount = 0;

        for (const student of students) {
            // Check if consent already exists for this target year
            const existing = await prisma.studentConsent.findUnique({
                where: {
                    studentId_academicYearId: {
                        studentId: student.id,
                        academicYearId: targetingAcademicYearId
                    }
                }
            });

            if (!existing) {
                await prisma.studentConsent.create({
                    data: {
                        studentId: student.id,
                        academicYearId: targetingAcademicYearId,
                        // token is auto-generated by the schema default(uuid())
                    }
                });
                createdCount++;
            }
        }

        return { success: true, message: `Generated ${createdCount} new consent links for ${classId}` };
    } catch (error: any) {
        console.error("Generate Consents Error:", error);
        return { success: false, error: "Failed to generate consent links." };
    }
}
