/**
 * 🔑 SOVEREIGN CAPABILITIES (CBAC - Capability-Based Access Control)
 * 
 * Each capability represents a specific atomic action within the ERP.
 * This is decoupled from 'Roles' to allow granular delegation.
 */
export type Capability = 
  | 'ADMISSION_CREATE'
  | 'ADMISSION_UPDATE'
  | 'STUDENT_DELETE'
  | 'RECORD_PAYMENT'
  | 'REVERSE_LEDGER'
  | 'VIEW_FINANCIALS'
  | 'VIEW_AUDIT_BIN'
  | 'ARCHIVE_STUDENT'
  | 'RESTORE_STUDENT'
  | 'ACADEMIC_CONFIG'
  | 'HR_PAYROLL'
  | 'INVENTORY_MANAGE'
  | 'TRANSPORT_MANAGE'
  | 'STAFF_MANAGE';

export interface SovereignRoleData {
  name: string;
  capabilities: Record<Capability, boolean>;
}

/**
 * 🏫 15-ROLE INDUSTRY STANDARDS
 * Default capability bundles for a premium School ERP.
 */
export const STANDARD_ROLES: Record<string, Record<Capability, boolean>> = {
  OWNER: {
    ADMISSION_CREATE: true, ADMISSION_UPDATE: true, STUDENT_DELETE: true,
    RECORD_PAYMENT: true, REVERSE_LEDGER: true, VIEW_FINANCIALS: true,
    VIEW_AUDIT_BIN: true, ARCHIVE_STUDENT: true, RESTORE_STUDENT: true,
    ACADEMIC_CONFIG: true, HR_PAYROLL: true, INVENTORY_MANAGE: true,
    TRANSPORT_MANAGE: true, STAFF_MANAGE: true
  },
  ACCOUNTANT: {
    ADMISSION_CREATE: false, ADMISSION_UPDATE: false, STUDENT_DELETE: false,
    RECORD_PAYMENT: true, REVERSE_LEDGER: true, VIEW_FINANCIALS: true,
    VIEW_AUDIT_BIN: false, ARCHIVE_STUDENT: false, RESTORE_STUDENT: false,
    ACADEMIC_CONFIG: false, HR_PAYROLL: true, INVENTORY_MANAGE: true,
    TRANSPORT_MANAGE: true, STAFF_MANAGE: false
  },
  FEE_COLLECTOR: {
    ADMISSION_CREATE: true, ADMISSION_UPDATE: false, STUDENT_DELETE: false,
    RECORD_PAYMENT: true, REVERSE_LEDGER: false, VIEW_FINANCIALS: true,
    VIEW_AUDIT_BIN: false, ARCHIVE_STUDENT: false, RESTORE_STUDENT: false,
    ACADEMIC_CONFIG: false, HR_PAYROLL: false, INVENTORY_MANAGE: false,
    TRANSPORT_MANAGE: false, STAFF_MANAGE: false
  },
  PRINCIPAL: {
    ADMISSION_CREATE: true, ADMISSION_UPDATE: true, STUDENT_DELETE: false,
    RECORD_PAYMENT: true, REVERSE_LEDGER: true, VIEW_FINANCIALS: true,
    VIEW_AUDIT_BIN: true, ARCHIVE_STUDENT: true, RESTORE_STUDENT: false,
    ACADEMIC_CONFIG: true, HR_PAYROLL: false, INVENTORY_MANAGE: true,
    TRANSPORT_MANAGE: true, STAFF_MANAGE: true
  },
  ACADEMIC_COORDINATOR: {
    ADMISSION_CREATE: true, ADMISSION_UPDATE: true, STUDENT_DELETE: false,
    RECORD_PAYMENT: false, REVERSE_LEDGER: false, VIEW_FINANCIALS: false,
    VIEW_AUDIT_BIN: false, ARCHIVE_STUDENT: false, RESTORE_STUDENT: false,
    ACADEMIC_CONFIG: true, HR_PAYROLL: false, INVENTORY_MANAGE: false,
    TRANSPORT_MANAGE: false, STAFF_MANAGE: false
  },
  EXAM_CONTROLLER: {
    ADMISSION_CREATE: false, ADMISSION_UPDATE: false, STUDENT_DELETE: false,
    RECORD_PAYMENT: false, REVERSE_LEDGER: false, VIEW_FINANCIALS: false,
    VIEW_AUDIT_BIN: false, ARCHIVE_STUDENT: false, RESTORE_STUDENT: false,
    ACADEMIC_CONFIG: true, HR_PAYROLL: false, INVENTORY_MANAGE: false,
    TRANSPORT_MANAGE: false, STAFF_MANAGE: false
  },
  TEACHER: {
    ADMISSION_CREATE: false, ADMISSION_UPDATE: false, STUDENT_DELETE: false,
    RECORD_PAYMENT: false, REVERSE_LEDGER: false, VIEW_FINANCIALS: false,
    VIEW_AUDIT_BIN: false, ARCHIVE_STUDENT: false, RESTORE_STUDENT: false,
    ACADEMIC_CONFIG: false, HR_PAYROLL: false, INVENTORY_MANAGE: false,
    TRANSPORT_MANAGE: false, STAFF_MANAGE: false
  },
  LIBRARIAN: {
    ADMISSION_CREATE: false, ADMISSION_UPDATE: false, STUDENT_DELETE: false,
    RECORD_PAYMENT: false, REVERSE_LEDGER: false, VIEW_FINANCIALS: false,
    VIEW_AUDIT_BIN: false, ARCHIVE_STUDENT: false, RESTORE_STUDENT: false,
    ACADEMIC_CONFIG: false, HR_PAYROLL: false, INVENTORY_MANAGE: true,
    TRANSPORT_MANAGE: false, STAFF_MANAGE: false
  },
  TRANSPORT_MANAGER: {
    ADMISSION_CREATE: false, ADMISSION_UPDATE: false, STUDENT_DELETE: false,
    RECORD_PAYMENT: false, REVERSE_LEDGER: false, VIEW_FINANCIALS: false,
    VIEW_AUDIT_BIN: false, ARCHIVE_STUDENT: false, RESTORE_STUDENT: false,
    ACADEMIC_CONFIG: false, HR_PAYROLL: false, INVENTORY_MANAGE: false,
    TRANSPORT_MANAGE: true, STAFF_MANAGE: false
  },
  STORE_MANAGER: {
    ADMISSION_CREATE: false, ADMISSION_UPDATE: false, STUDENT_DELETE: false,
    RECORD_PAYMENT: false, REVERSE_LEDGER: false, VIEW_FINANCIALS: false,
    VIEW_AUDIT_BIN: false, ARCHIVE_STUDENT: false, RESTORE_STUDENT: false,
    ACADEMIC_CONFIG: false, HR_PAYROLL: false, INVENTORY_MANAGE: true,
    TRANSPORT_MANAGE: false, STAFF_MANAGE: false
  },
  HR_MANAGER: {
    ADMISSION_CREATE: false, ADMISSION_UPDATE: false, STUDENT_DELETE: false,
    RECORD_PAYMENT: false, REVERSE_LEDGER: false, VIEW_FINANCIALS: false,
    VIEW_AUDIT_BIN: false, ARCHIVE_STUDENT: false, RESTORE_STUDENT: false,
    ACADEMIC_CONFIG: false, HR_PAYROLL: true, INVENTORY_MANAGE: false,
    TRANSPORT_MANAGE: false, STAFF_MANAGE: true
  },
  RECEPTIONIST: {
    ADMISSION_CREATE: true, ADMISSION_UPDATE: false, STUDENT_DELETE: false,
    RECORD_PAYMENT: false, REVERSE_LEDGER: false, VIEW_FINANCIALS: false,
    VIEW_AUDIT_BIN: false, ARCHIVE_STUDENT: false, RESTORE_STUDENT: false,
    ACADEMIC_CONFIG: false, HR_PAYROLL: false, INVENTORY_MANAGE: false,
    TRANSPORT_MANAGE: false, STAFF_MANAGE: false
  },
  SECURITY: {
    ADMISSION_CREATE: false, ADMISSION_UPDATE: false, STUDENT_DELETE: false,
    RECORD_PAYMENT: false, REVERSE_LEDGER: false, VIEW_FINANCIALS: false,
    VIEW_AUDIT_BIN: false, ARCHIVE_STUDENT: false, RESTORE_STUDENT: false,
    ACADEMIC_CONFIG: false, HR_PAYROLL: false, INVENTORY_MANAGE: false,
    TRANSPORT_MANAGE: false, STAFF_MANAGE: false
  },
  PARENT: {
    ADMISSION_CREATE: false, ADMISSION_UPDATE: false, STUDENT_DELETE: false,
    RECORD_PAYMENT: false, REVERSE_LEDGER: false, VIEW_FINANCIALS: false,
    VIEW_AUDIT_BIN: false, ARCHIVE_STUDENT: false, RESTORE_STUDENT: false,
    ACADEMIC_CONFIG: false, HR_PAYROLL: false, INVENTORY_MANAGE: false,
    TRANSPORT_MANAGE: false, STAFF_MANAGE: false
  },
  STUDENT: {
    ADMISSION_CREATE: false, ADMISSION_UPDATE: false, STUDENT_DELETE: false,
    RECORD_PAYMENT: false, REVERSE_LEDGER: false, VIEW_FINANCIALS: false,
    VIEW_AUDIT_BIN: false, ARCHIVE_STUDENT: false, RESTORE_STUDENT: false,
    ACADEMIC_CONFIG: false, HR_PAYROLL: false, INVENTORY_MANAGE: false,
    TRANSPORT_MANAGE: false, STAFF_MANAGE: false
  }
};
