import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();
const BRANCH_ID = "VIVES-RCB";

async function main() {
  console.log("=== STRICT AUDIT OF ALL STUDENT PROFILES IN VIVES-RCB ===");

  const allStudents = await prisma.student.findMany({
    where: { branchId: BRANCH_ID },
    include: {
      family: true,
      collections: true,
      academic: { include: { class: true } }
    }
  });

  console.log(`Total Student Records in DB for ${BRANCH_ID}: ${allStudents.length}`);

  let autoGeneratedCount = 0;
  let registerCount = 0;

  const autoGeneratedList: any[] = [];
  const registerList: any[] = [];

  for (const s of allStudents) {
    const adm = s.admissionNumber || "";
    const isAutoGenerated = adm.startsWith("ADM-") || adm.startsWith("VIVES-RCB-2627-STU-") || adm.includes("PASTED");

    if (isAutoGenerated) {
      autoGeneratedCount++;
      autoGeneratedList.push(s);
    } else {
      registerCount++;
      registerList.push(s);
    }
  }

  console.log(`\n1. Register Admission Numbers (e.g. VR..., VS..., VM..., TEMP...): ${registerCount}`);
  console.log(`2. Auto-Generated / Draft Admission Numbers (e.g. ADM-..., VIVES-RCB-...): ${autoGeneratedCount}`);

  console.log("\nSample Register Students (First 15):");
  for (const s of registerList.slice(0, 15)) {
    console.log(`- ID: ${s.id} | AdmNo: "${s.admissionNumber}" | StudentName: "${s.firstName} ${s.lastName}" | Father: "${s.family?.fatherName}" | Collections: ${s.collections.length}`);
  }

  console.log("\nSample Auto-Generated / Draft Students (First 15):");
  for (const s of autoGeneratedList.slice(0, 15)) {
    console.log(`- ID: ${s.id} | AdmNo: "${s.admissionNumber}" | StudentName: "${s.firstName} ${s.lastName}" | Father: "${s.family?.fatherName}" | Collections: ${s.collections.length}`);
  }
}

main().catch(console.error).finally(() => prisma.$disconnect());
