import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();
const BRANCH_ID = "VIVES-RCB";

async function deleteStudentsSafely(studentIds: string[]) {
  if (studentIds.length === 0) return;

  const finRecords = await prisma.financialRecord.findMany({
    where: { studentId: { in: studentIds } },
    select: { id: true }
  });
  const finIds = finRecords.map(f => f.id);

  if (finIds.length > 0) {
    await prisma.studentFeeComponent.deleteMany({ where: { studentFinancialId: { in: finIds } } });
    await prisma.discount.deleteMany({ where: { studentFinancialId: { in: finIds } } });
  }

  const invoices = await prisma.feeInvoice.findMany({
    where: { studentId: { in: studentIds } },
    select: { id: true }
  });
  const invoiceIds = invoices.map(i => i.id);

  if (invoiceIds.length > 0) {
    await prisma.feeInvoiceItem.deleteMany({ where: { invoiceId: { in: invoiceIds } } });
    await prisma.feeInvoice.deleteMany({ where: { id: { in: invoiceIds } } });
  }

  // Delete all child records referencing studentId
  const deleteOpts = { where: { studentId: { in: studentIds } } };
  
  try { await prisma.studentAcademicYear.deleteMany(deleteOpts); } catch (e) {}
  try { await (prisma as any).studentGuardian?.deleteMany(deleteOpts); } catch (e) {}
  try { await (prisma as any).address?.deleteMany(deleteOpts); } catch (e) {}
  try { await (prisma as any).medicalRecord?.deleteMany(deleteOpts); } catch (e) {}
  try { await (prisma as any).bankDetail?.deleteMany(deleteOpts); } catch (e) {}
  try { await (prisma as any).previousSchool?.deleteMany(deleteOpts); } catch (e) {}
  try { await (prisma as any).document?.deleteMany(deleteOpts); } catch (e) {}
  try { await prisma.academicRecord.deleteMany(deleteOpts); } catch (e) {}
  try { await prisma.familyDetail.deleteMany(deleteOpts); } catch (e) {}
  try { await prisma.transportDetail.deleteMany(deleteOpts); } catch (e) {}
  try { await prisma.financialRecord.deleteMany(deleteOpts); } catch (e) {}

  await prisma.student.deleteMany({ where: { id: { in: studentIds } } });
}

async function main() {
  console.log("=== ENFORCING RULEBOOK ON STUDENT MASTER PROFILES IN VIVES-RCB ===");

  const allStudents = await prisma.student.findMany({
    where: { branchId: BRANCH_ID },
    include: {
      family: true,
      collections: true,
      academic: true
    }
  });

  console.log(`Starting Total Students in ${BRANCH_ID}: ${allStudents.length}`);

  // Step 1: Identify draft / auto-generated records with 0 collections
  const draftIdsToDelete: string[] = [];

  for (const s of allStudents) {
    const adm = s.admissionNumber || "";
    const isAutoGenerated = adm.startsWith("ADM-") || adm.startsWith("VIVES-RCB-2627-STU-") || adm.includes("PASTED") || adm === "null" || adm === "";

    if (isAutoGenerated && s.collections.length === 0) {
      draftIdsToDelete.push(s.id);
    }
  }

  console.log(`Deleting ${draftIdsToDelete.length} auto-generated / draft / null admission records...`);
  await deleteStudentsSafely(draftIdsToDelete);
  console.log(`Successfully deleted ${draftIdsToDelete.length} draft records.`);

  // Step 2: Deduplicate remaining student records by Register Admission Number
  const remainingStudents = await prisma.student.findMany({
    where: { branchId: BRANCH_ID },
    include: { collections: true, academic: true }
  });

  console.log(`\nRemaining Students after draft cleanup: ${remainingStudents.length}`);

  const admGroupMap = new Map<string, typeof remainingStudents>();
  for (const s of remainingStudents) {
    const key = (s.admissionNumber || "").trim().toUpperCase();
    if (!key) continue;
    if (!admGroupMap.has(key)) admGroupMap.set(key, []);
    admGroupMap.get(key)!.push(s);
  }

  const duplicateIdsToDelete: string[] = [];
  for (const [admKey, group] of admGroupMap.entries()) {
    if (group.length > 1) {
      group.sort((a, b) => {
        if (b.collections.length !== a.collections.length) {
          return b.collections.length - a.collections.length;
        }
        if (b.academic && !a.academic) return 1;
        if (a.academic && !b.academic) return -1;
        return 0;
      });

      for (let i = 1; i < group.length; i++) {
        if (group[i].collections.length === 0) {
          duplicateIdsToDelete.push(group[i].id);
        }
      }
    }
  }

  console.log(`Deduplicating ${duplicateIdsToDelete.length} duplicate empty student records...`);
  await deleteStudentsSafely(duplicateIdsToDelete);
  console.log(`Successfully deleted ${duplicateIdsToDelete.length} duplicate empty records.`);

  const finalStudentsCount = await prisma.student.count({ where: { branchId: BRANCH_ID } });
  const finalCollectionsCount = await prisma.collection.count({ where: { branchId: BRANCH_ID } });

  console.log(`\n========================================================`);
  console.log(`RULEBOOK ENFORCEMENT & MASTER CLEANUP COMPLETE!`);
  console.log(`Total Pure Register Students in DB: ${finalStudentsCount}`);
  console.log(`Total Collections Intact & Reconciled: ${finalCollectionsCount}`);
  console.log(`========================================================`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
